# Generated by Django 5.0 on 2023-12-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_participant_delete_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='role',
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
